version: "3.9"

services:
  airportexplorer_web:
    build: .
    container_name: airportexplorer_web
    restart: unless-stopped
    expose:
      - 9000
  airportexplorer_nginx:
    build: ./nginx
    container_name: airportexplorer_nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: airportexplorer.temfack.com
      LETSENCRYPT_HOST: airportexplorer.temfack.com
      LETSENCRYPT_EMAIL: hello@temfack.com

  airportexplorer_redis:
    image: redis:7-alpine
    container_name: airportexplorer_redis
    restart: unless-stopped

  airportexplorer_celery:
    build: .
    command: celery --app=run.celery_app worker -l INFO
    container_name: airportexplorer_celery
    restart: unless-stopped
    depends_on:
      - airportexplorer_redis

#Use this configuration in production with nginx-proxy container
networks:
  default:
    name: nginx-proxy
    external: true
