version: "3.7"

services:
  airportexplorer:
    build: .
    container_name: airportexplorer
    restart: unless-stopped
    expose:
      - 9000
  airportexplorer_nginx:
    build: ./airportexplorer_nginx
    container_name: airportexplorer_nginx
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: airportexplorer.temfack.com
      LETSENCRYPT_HOST: airportexplorer.temfack.com
      LETSENCRYPT_EMAIL: dericktemfack@gmail.com


#Use this configuration in production with nginx-proxy container
networks:
  default:
    name: nginx-proxy
    external: true
