version: "3.7"

services:
  airportexplorerdev:
    build: .
    container_name: airportexplorerdev
    restart: unless-stopped
    expose:
      - 9000
  airportexplorerdev_nginx:
    build: ./nginx
    container_name: airportexplorerdev_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
